### ISSUE TITLE
configuration for two RS in same ASN

### ISSUE THREAD

**Issue by nitesh058** [pierky/arouteserver#100]
I want to make i-bgp b/w two Route Server with same ASN, only router ID and IP is different for both RS.
What will be syntax or where we need to put either in client.yml or general.yml. Please help

**Comment by pierky** [comment]
Please check the docs: https://arouteserver.readthedocs.io/en/latest/CONFIG.html#yaml-files-inclusion-and-environment-variables-expansion

This should help.

**Comment by bluikko** [comment]
The OP is not exactly clear on what is the intended question.  
But depending on what it means it could be taken to mean an interesting point: could the current system be optimized?

I believe that currently multiple discrete runs are required for multiple router IDs&IP addresses in the same ASN.  
For example, I am currently doing 1 run for RS 192.0.2.1 and then a second run for 192.0.2.2 and so on. But this is actually somewhat inefficient, even if there is caching of the enricher results.

I am not familiar enough with the code base to evaluate whether there could be gains in some kind of other approach (for example, being able to declare a list of router IDs/IP addresses) to generating very similar configs for multiple RS (for example where only the router ID/IP address changes from .1 to .2).
