### ISSUE TITLE
reject cause not being tagged?

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#11]
I have an arouteserver openbgpd instance

```
$ egrep -A1 "\"tag\"|reject_cause" rs2.yml
      policy: "tag"

    reject_cause:
      lrg: rs_as:9:dyn_val
```

but it appears the bgpd configuration bits that actually set those communities are not present:

```
job@rs2:~/snapshots$ grep 53339:9 /etc/bgpd.conf
job@rs2:~/snapshots$
```
Any idea what I've done wrong?

**Comment by pierky** [comment]
It was actually a bug: features offered using large communities only were not taken into account during the config building process. Should be fixed now. Thanks @job.
