### ISSUE TITLE
Remove RGNET from whois sources

### ISSUE THREAD

**Issue by bluikko** [pierky/arouteserver#111]
The whois source `RGNET` is not currently available from the `rr1.ntt.net` whois servers. Would it make sense to remove it from the default `arouteserver.yml` setting `bgpq3_sources`?

I do not know if this is a permanent change and asking around a bit did not result in any further information either.

This database seems to contain only about 50 entries that do not seem critical.

**Comment by pierky** [comment]
Hi @bluikko,

I'm going to remove it from the default values (next version will be out soon).

In the meantime: have you heard anything about what's going on with that source? I couldn't find any information as well.
