### ISSUE TITLE
Deprecate ARIN-WHOIS data source

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#116]
The ARIN Advisory Counsel recommended the ARIN Board of Trustees to deprecate the "ARIN AS Origins" feature in the ARIN WHOIS database

https://www.arin.net/participate/policy/drafts/2021_8/

Probably best to deprecate it / remove it in Arouteserver

**Comment by lukastribus** [comment]
Are you suggesting to remove it immediately?

Wouldn't it be better to just let ARIN actually deprecated this in the database based on their agreed upon time frame with the community (The removal of ‘OriginAs’ fields from December 31st 2024 to 24 months after board adoption.) as opposed to anticipate this in arouteserver?

Of course if this is a feature with basically zero usage in ARIN land, then there is no point in delaying the removal. Is that the case?

**Comment by job** [comment]
Arouteserver doesn't use ARIN directly, but an intermediate data relay; which ceased to exist. Unless someone volunteers to rebuild the feature I think we can just move to deprecation.

**Comment by job** [comment]
@lukastribus also good to keep in mind that operators should remove dependencies on this data source *well in advance* of the official deprecation

**Comment by pierky** [comment]
I'm leaning towards an early deprecation of the feature.

The feature is disabled by default in ARouteServer, however, the "rich" configuration proposed when the `configure` command is executed has it turned on.

My plan is to change the behaviour of the `configure` command, to not enable the feature anymore, and also to leave `use_arin_bulk_whois_data.source` empty (today it contains the URL of arin-whois-originas.json.bz2 on arin-whois-originas.json.bz2). In addition, I'll have the tool generating a warning message in case the feature will be enabled, pointing to the communication from ARIN mentioned in the first message of this issue.

Operators who are using that feature today can already disable it by setting `use_arin_bulk_whois_data.enable` to `False`, or providing an alternative path for the source file.

**Comment by pierky** [comment]
Thanks for filing this issue @job.

A new release (v1.19.0) will be out as soon as CI/CD completes. Tt contains the deprecation of the feature, which is already in master.
