### ISSUE TITLE
feature request: add anchors to route server policy textual representation, other minor issues

### ISSUE THREAD

**Issue by bluikko** [pierky/arouteserver#119]
It would be useful if the route server policy textual representation HTML file would have anchors at the various headers (and sub-headers) so when referring other parties to the policy we could point them directly to the relevant section.

Just adding anchors in the source would be sufficient, even better if there could be a small Unicode icon for copying the anchor link (haven't looked at how exactly that could be done in the absence of CSS); or maybe they could just simply be links to itself so that the link to the anchor could be copied with right-click? Feel free to bikeshed further...

Also a few small points I noticed while looking at the HTML file source:
- Some of the `a href` links are missing protocol + `:` and start with `//domain.tld/...` - GTSM, ADD_PATH RFC links.
- AS path "private/invalid" links to http://mailman.nanog.org/pipermail/nanog/2016-June/086078.html which seems to have nothing to do with private or invalid ASNs - I am seeing a non-technical mail with subject "IPv6 is better than ipv4"?

**Comment by pierky** [comment]
Thanks @bluikko, I'm on it...

**Comment by pierky** [comment]
Going to ship this set of enhancements/fixes in v1.20, which is currently going through the CI/CD pipeline and hopefully will be out in 1 hour or so from now.
Thanks for reporting it!
