### ISSUE TITLE
ipv4 table entry in bird config

### ISSUE THREAD

**Issue by jayhanke** [pierky/arouteserver#123]
Bird config comes back with syntax error after upgrading to arouteserver 1.21.1

BIRD 1.6.6 ready.
Reading configuration from /etc/bird/bird.conf
/etc/bird/bird.conf:16:1 syntax error

Looking at the generated config file it appears that the line

ipv4 table master4 sorted;

has changed from:

table master sorted;

**Comment by pierky** [comment]
@jayhanke would you mind sharing the command that you're using to build your config?
Please note that as of 1.21.0 the default target version of BIRD became 2.0: https://github.com/pierky/arouteserver/blob/master/CHANGES.rst#1210 Now `--target-version` must be used to generate BIRD 1.6 configs.

**Comment by jayhanke** [comment]
That was it. I set the --target-version and it worked right away

**Comment by jayhanke** [comment]
target version not set
