### ISSUE TITLE
openbgpd support

### ISSUE THREAD

**Issue by job** [pierky/arouteserver#2]
We should support `openbgpd` too next to `BIRD`. In terms of features OpenBGPD & BIRD are alike, but configuration method is different.

**Comment by job** [comment]
step 1) figure out how to run openbsd + openbgpd inside docker, i suppose with a KVM wrapper we can do this (so stack is docker -> kvm -> openbsd -> openbgpd)

**Comment by pierky** [comment]
This is definitely the next feature I'll work on. I've already started the same work on GoBGP but I think I'll pause it.
Configuration method and syntax should be not a big problem. Validation tests are a pain.
I see that something exists to run kvm VMs inside Docker but I never tried it and I'm not sure if/how it works.

I was also thinking something like this for live tests on OpenBGPD:
```
  docker          bird  bird  bird          rs clients
                   |     |     |
  virtual bridge =========================
                           |
  kvm                   openbsd             route server
```

I have to check how I can bridge the Docker network where clients are connected to the network where the kvm VM is connected. And also how I can connect to the kvm VM from the Python script that instantiated it: ssh is an option but host and the virtual network must reach each other to work.

**Comment by job** [comment]
Perhaps take a look at this project https://github.com/plajjan/vrnetlab, here docker is used to wrap around arbitrary operating systems such as IOS XR or Junos. it's probably entirely feasible to do the same with openbsd/openbgpd.

If that fails, your bridging approach is worth a shot too.

**Comment by pierky** [comment]
It seems that this is working fine:

```
sudo virt-install \
-n openbsd1 \
-r 512 \
--vcpus=1 \
--os-variant=openbsd4 \
--accelerate \
-v -c install60.iso \
-w bridge:br-2d2956ce4b64 \
--graphics vnc,listen=0.0.0.0 \
--disk path=~/vms/openbsd1.qcow2,size=5,format=qcow2
```

where `bridge:br-2d2956ce4b64` points to the bridge interface created by Docker.

This solution allows to control OpenBGPD using an ssh connection from the host where Python and kvm are running and also allows Docker containers (that is, rs clients) to be on the same net of the rs.

**Comment by pierky** [comment]
OpenBGPD support has been added in v0.4.0, even if some [limitations](https://arouteserver.readthedocs.io/en/latest/CONFIG.html#caveats-and-limitations).
Live tests also work fine locally, but not on TravisCI, because AFAIK there's no way to run VMs there.

**Comment by job** [comment]
openbsd 6.1 has large comms support, that will probably released in a few
weeks.

**Comment by pierky** [comment]
Yes I know, they will be enabled as soon as it will be released.
