### ISSUE TITLE
Error reloading BIRD6 when IPv6 neighbors are established

### ISSUE THREAD

**Issue by killafunkinmofo** [pierky/arouteserver#20]
Error Unknown instruction 8574 in same (~) from BIRD when neighbors are established and trying to reload config with "birdc6 configure".

It looks like BIRD has fixed the problem but probably only pre-release version: http://bird.network.cz/pipermail/bird-users/2017-January/010880.html

I modified my bird6.conf import policy for peer:
From:
   if net !~ [2000::/3+] then
To:
    if !(net ~ [2000::/3+]) then

It appears to work correctly after the change:
It rejected the prefix it was intended to match: prefix is not in IPv6 Global Unicast space - REJECTING 9ff2:1::/32

**Comment by pierky** [comment]
Thanks @killafunkinmofo! Fixed in 0.14.1.
