### ISSUE TITLE
bgp.last doesn't support aggregated origins

### ISSUE THREAD

**Issue by s1sfa** [pierky/arouteserver#34]
When a network that is advertising is aggregating like [this](https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/5441-aggregation.html#aggregatingwiththeassetargument) using aggregation. bgp_path.last returns a 0 so the origin as checks naturally fail when checking AS0 agains the IRRDB lists.

In my generated bird.conf I replaced bgp_path.last with bgp_path.last_nonaggregated which didn't seem to cause any problems and fixed the rejected routes in my small set of routes. So naturally if I change every occurrence of bgp_path.last to bgp_path.last_nonaggregated in the whole repo it should fix this problem :)

**Comment by pierky** [comment]
Hi @s1sfa, thanks for filing this issue and for the PR.
I've tested it and merged it, v0.19.1 is building right now and will be out in a few minutes.
