### ISSUE TITLE
Not using default configuration paths

### ISSUE THREAD

**Issue by benerudolph** [pierky/arouteserver#6]
Other than stated in the documentation
> By default, ARouteServer looks for this [arouteserver.yml] file in `~/arouteserver` and `/etc/arouteserver/`

ARouteServer raises en error “Configuration file not found”. This is likely because self.cfg is replaced with self.default which has `cfg_dir=None` (pierky/arouteserver/config/program.py:44). Expected behavior is to look for arouteserver.yml at the specified locations.

Workaround is to specify optional parameter `--cfg` and path to arouteserver.yml.

**Comment by pierky** [comment]
Thanks it should be fixed now
