### ISSUE TITLE
Textual representation HTML formatting problem in "Reject reasons" table

### ISSUE THREAD

**Issue by bluikko** [pierky/arouteserver#71]
There is some problem with the HTML template: the "Reject reasons" table is rendered wrong.

At least on a 1920x1080 screen (no scaling) all the rows after the first are split with a newline after "ID" column:
![image](https://user-images.githubusercontent.com/14869000/115352274-62121d80-a1e1-11eb-8035-1c90023aef4d.png)

The configuration for reject reasons is using default values from the docker image run. One notable difference to https://arouteserver.readthedocs.io/en/latest/_static/examples_rich.html is that the example does not include any of the communities: it just includes ID and reason.

Using Chromium 90 on Windows.

Will try to take a look at this in more detail at some point.

**Comment by bluikko** [comment]
There seems to be an extra `<tr>` element in the rendered HTML file:
```html
  <tr>
    <td align=right>1</td>
      <tr> <--- here
    <td>Invalid AS_PATH length</td>
    <td>65520:1</td>
    <td>rt:65520:1</td>
[...]
```

**Comment by pierky** [comment]
This is WIP in the dev branch, it should be already fixed. Details in https://github.com/pierky/arouteserver/pull/68#issuecomment-825135622

**Comment by pierky** [comment]
This should be fixed now in v1.5.1. Thanks for the feedback (and for proposing the solution!)

**Comment by bluikko** [comment]
Looks good indeed, didn't get round to updating until 1.10.0.

**Comment by pierky** [comment]
> Looks good indeed, didn't get round to updating until 1.10.0.

Thanks for the feedback!
