### ISSUE TITLE
Validate client configuration file without building output file

### ISSUE THREAD

**Issue by vilhelmprytz** [pierky/arouteserver#79]
Hello!

Is there any possibility that arouteserver can be used to validate that the client YAML file contains correct syntax without actually building the output configuration file (which can be time-consuming)?

Thanks!

**Comment by pierky** [comment]
Hello @vilhelmprytz, thanks for the feedback, a sub-command that does it doesn't currently exist, but it sounds like a nice addition for the project. I'll take it into account for the future.

**Comment by pierky** [comment]
#82 was merged into dev, the new command will be released in 1.10.0.

Thanks for this @vilhelmprytz.
