### ISSUE TITLE
RPKI validation custom community formatting in textual representation file

### ISSUE THREAD

**Issue by bluikko** [pierky/arouteserver#83]
After adding custom RPKI validation communities implemented as part of #78 the route server configuration textual representation file has a small cosmetic problem visible in this screenshot (off latest Chrome):
![image](https://user-images.githubusercontent.com/14869000/130403260-0f9be847-6a32-4eb5-b2e5-0020e5adb83f.png)
The two new unordered list items have their bullet point on a line by themselves and the text to go with that bullet point is on the following line.
Additionally it looks like the bullet point is indented wrong, closer to the left margin than the previous two list items.

**Comment by pierky** [comment]
Hello @bluikko, thanks for filing this issue.
I believe I identified and fixed it (d6c68c4dd7eacb915702bfadf13dc95bf4f682d9).

Right now the CI/CD pipeline is running to build (and if successful push) v1.10.1-alpha1, the candidate release for the v1.10.1 where the bug will be fixed.

It would be great if later (let's say in 1 hour from now) you could check out https://test.pypi.org/project/arouteserver/, the test instance of PyPi, where alpa releases are pushed, and in case the -alpha1 made to it, to give it a test. Instructions on how to install alpha releases from the test instance of PyPi can be found here: https://arouteserver.readthedocs.io/en/latest/INSTALLATION.html#development-and-pre-release-versions

Thanks

**Comment by pierky** [comment]
https://test.pypi.org/project/arouteserver/1.10.1a1/ is out in pre-release, on PyPi test instance.

**Comment by bluikko** [comment]
@pierky I am using the Docker image. But 1.10.1-alpha1 does indeed fix the formatting.

**Comment by pierky** [comment]
> @pierky I am using the Docker image. But 1.10.1-alpha1 does indeed fix the formatting.

Thanks @bluikko, the final v1.10.1 is being built and it will be out soon (about 1 h from now).
