### ISSUE TITLE
An error occurred while reading program configuration Unknown statement: cfg

### ISSUE THREAD

**Issue by christheradioguy** [pierky/arouteserver#84]
Hello,

Attempting to setup a brand new install of arouteserver and receiving the following error with the default configuration: "n error occurred while reading program configuration Unknown statement: cfg"

Basically, I have done the following after installing it:
* export PYTHONPATH="`pwd`"
* ./scripts/arouteserver setup
* cd etc/
* mv general.distrib.yml general.yml
*  /opt/arouteserver/scripts/arouteserver bird --ip-ver 4 --local-files-dir /etc/bird --use-local-files header --cfg /opt/arouteserver/etc/general.yml -o /etc/bird/bird.conf 

At which point I receive the error.  Anyone ever encountered this before?

**Comment by pierky** [comment]
Hello @christheradioguy,

I’ll try to reproduce the issue ASAP and see if I’m able to get your same situation and error.

Have you tried following the installation and setup instructions documented here? https://arouteserver.readthedocs.io/en/latest/INSTALLATION.html

**Comment by christheradioguy** [comment]
Thanks for the speedy reply.  I had used the "install from github" instructions to build locally, except I had installed to /opt/arouteserver rather then ~/src/arouteserver

**Comment by pierky** [comment]
Not sure about your steps, it's not clear to me what you used for the `setup` command (did you use /opt/arouteserver/etc?), nor why you did `mv general.distrib.yml general.yml` after the configure (did you do the `configure` command? did you want to override the configuration generated by the `configure` command with the file which is distributed with the package?), anyway I've spotted an error. The `--cfg` argument wants the arouteserver.yml file path, and not the general.yml file. Maybe you can try again in that way?

**Comment by christheradioguy** [comment]
Thanks for the reply, I was originally trying to use an old configuration, then I started messing with just trying to get it to work without following the setup guide which is why I started poking around with the distrib file.  

Now with blasting away the old config and rerunning with --cfg=arouteserver.yml I can confirm it is working as expected.

**Comment by pierky** [comment]
Hi, thanks for the feedback. I'm going to close this issue as it seems to me that is solved.
