### ISSUE TITLE
Can I run bgp route-server and route-client in one docker?

### ISSUE THREAD

**Issue by grandnew** [pierky/arouteserver#94]
Hi, all. Is there anyway to run bgp route-server and route-client in one docker?

**Comment by pierky** [comment]
Hello @grandnew, not sure what you mean with "one docker", if you mean having one route-server-like BGP speaker + one route-server-like client BGP speaker inside the same Docker container I think it should be possible, but tricky. However, I believe your question is off topic regarding this repository; please use other resources on the Internet to ask help on this.

I'll be happy to provide assistance for what concerns ARouteServer here.

**Comment by grandnew** [comment]
Hi, @pierky.
Yeah I mean that. But how to construct a route-server-like client BGP speaker using ARouteServer?
Thanks!
